# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ssynthesia/ghostcity/git/codename-autosinta/src/autosinta/ui/about_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(456, 300)
        self.btns = QtWidgets.QDialogButtonBox(Dialog)
        self.btns.setGeometry(QtCore.QRect(370, 10, 81, 281))
        self.btns.setOrientation(QtCore.Qt.Vertical)
        self.btns.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.btns.setObjectName("btns")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(10, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.text = QtWidgets.QTextBrowser(Dialog)
        self.text.setGeometry(QtCore.QRect(10, 50, 341, 241))
        self.text.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.text.setObjectName("text")

        self.retranslateUi(Dialog)
        self.btns.accepted.connect(Dialog.accept) # type: ignore
        self.btns.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About"))
        self.title.setText(_translate("Dialog", "About AutoSINTA"))
        self.text.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">AutoSINTA</span> is an unofficial program that synchronizes author publication data in <a href=\"https://sinta.kemdikbud.go.id/authorverification\"><span style=\" text-decoration: underline; color:#0000ff;\">SINTA</span></a>. Using automation and looping, this program accesses the API of SINTA such that the synchronization of author publication data in SINTA can be performed in bulk without human labor.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Created in 2024 by <span style=\" font-weight:600;\">Samarthya Lykamanuella</span> in association with Directorate of Research and Community Service of Satya Wacana Christian University Salatiga, Indonesia.</p></body></html>"))
